version: 2
jobs:
  build:
    working_directory: ~/embulk-filter-decrypt
    docker:
      - image: openjdk:8-jdk
    environment:
      TERM: "dumb"
      # from https://discuss.circleci.com/t/circle-ci-v2-and-android-memory-issues/11207
      JVM_OPTS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: EMBULK_FILTER_DECRYPT_TEST_CONFIG=`pwd`/ci/ci_decrypt.yml ./gradlew clean check checkstyle jacocoTestReport --no-daemon --max-workers=2
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results
          destination: test-results
