name: Build and test
on: push
env:
  TERM: "dumb"
  _JAVA_OPTIONS: "-Xmx4096m"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Dependencies
      run: ./gradlew downloadDependencies
    - name: Run Tests
      run: env EMBULK_FILTER_DECRYPT_TEST_CONFIG=`pwd`/ci/ci_decrypt.yml ./gradlew clean check checkstyle jacocoTestReport
